#include <fkadeal>
the hig ad rugged relif nature of ethiopia is mostly accelerating the magnitude of soil erosion, 
what are the mechanisms that are widely applied in the context of ethiopia to control soil erosion ?

  
Discuss o the major problems of urban centres of Ethiopia
>>Urban centres in Ethiopia are characterised by a variety of socio-economic problems,
mainly poverty, the higher rate of dependency, unemployment, and illiteracy.

>>3<<Explain brifly the contribution and challenges of tourism in ethiopia
>contributons

>>Tourism development is important tool in promoting economic growth, alleviating poverty and advancing food security. 
  Tourism is a principal export for 83% of Ethiopia and it is the most significant source of foreign exchange
>>according to (WTTC) Travel and Tourism contributed $7.4 billion to the country’s economy, an increase of 9.4% of Ethiopia’s total economy.
Supported 3.32% total employment
Was primarily driven by leisure travellers: 79% of the spending was generated by leisure visitors and 21% from business travellers
Is strongly weighted towards international travel: 77% of spending came from international travellers and 23% from domestic
>challenges are 
>>political unrest, The outbreak of war, famine, 
unfavorable economic policies and poor infras- tructure development have been among the major factors hindering the growth of tourism in Ethiopia.

>>4<< Describe the contributions and challenges of transport sector to the ethiopian economy
>>The city's current transportation system is marked by a poor access network, 
  lack of adequate public transport services, continuous increases in transport fees, 
  lack of smooth traffic flow and infrastructure for pedestrians, and a high rate of traffic accidents
>>Some of the barriers are lack of knowledge, poor transportation system, 
lack of government support, lack of infrastructure and no tourism planning and 
Although security is a major challenge to the travel and tourism industry,
  
>>public transport system and road construction underway in all corners of the city commuters face daily transport challenges and traffic congestion, 
especially during rush hours, when on average one needs to wait for at least 15 to 25 minutes to get into a bus or taxi.
  
>> public transport services, continuous increases in transport fees, lack of smooth traffic flow and infrastructure for pedestrians, 
and a high rate of traffic accidents.

>> ecnomey
>>Transport system helps to send raw materials, fuel and machineries to different industries at right time and runs the industry. 
  It helps to raise the production of raw materials, fuels and machineries etc. by providing market to it. It widens the size of the market
